### PR TITLE
mv /root/owncloud/ to /root/

### PR DESCRIPTION
**Pull request by voroyam**
because there is no folder /root/owncloud

### CODE REVIEW

**Comment by voroyam** [comment]
@spaceone can you merge this? :)

**Comment by spaceone** [comment]
Are you sure that this config file is evaluated then? Otherwise the file could also be deleted if it's not necessary anymore. There is another reference in the README files to the old path.

**Comment by voroyam** [comment]
Reviewing PRs at 4 AM. You are either early up or late up :)

So let's summarize what we know about this.

It's a optional config file, which can be used to customize the sub path of the shibboleth. Right?

I also checked in a previous oC version (10.0.4). There the /root/owncloud/ folder exists. These are the contents:

```
root@owncl-29343846: ~/owncloud # ls
config.php  database.php  domains.php  license.php  marketplace.php  objectstore.php  php.ini  subpath.conf  toppath.conf  utf8mb4.php
```

as you can see - there are various configs and php files. but none of these files are symlinked, we checked. No one from the current team knows why this folder is there or why those files are there.

My theory is, that the developer who maintained the docker image wanted to restructure the app from config file management to a variables management. This was an early form of this restructure. In the current form we have 1 file overwrite.config.php with all the variables from the php files.

Also the .conf name and the nature of the file suggests that it has to go in to the apache2 conf available dir, but since it's not there in the old app nor in the new app I suggest that it's really optional.

Currently the installation script breaks because of this file, because in the new app there is no folder for this file. So I suggest we just copy it to root, and if we need it later on we can copy it to another place. But for now the focus should be that the script does not break.

**Comment by spaceone** [comment]
Okay, then i'll merge it.

**Pull request merged**
